name: Build & Deploy
on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NoseJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            mkdir test
            cd test
            git clone git@github.com:themaxtuple/portfolio.git
            echo 'Deployment successful to Digital Ocean'
