name: Build and Deploy
on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd /home
            git clone git@github.com:themaxtuple/portfolio.git
            cd /home/portfolio
            npm run build
            sudo cp -r /home/portfolio/build/* /var/www/html/
            echo 'Deployment successful to Digital Ocean'
